### ISSUE TITLE
httpget :skull:

### ISSUE THREAD

**Issue by anhtlauncher** [0xVienna/Celery#8]
why i cant use?
how tf
![image](https://github.com/0xVienna/Celery/assets/99712037/c67b1443-5fd6-4925-90e6-718cb548ae1b)

**Comment by 0xVienna** [comment]
Fixed. I added celery installer. Update celery by deleting the whole celery and re-download the newer release or from the website

**Comment by anhtlauncher** [comment]
> Fixed. I added celery installer. Update celery by deleting the whole celery and re-download the newer release or from the website

source? :trollface:
